### ISSUE TITLE
Online interactive XRD calculator

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/XRD#11]
something todo.

**Comment by qzhu2017** [comment]
@sayred1 @sabaronett 

I just added a sample script to make the interactive plot for PXRD. This should serve as a basis for our further web project.

**Comment by qzhu2017** [comment]
@sayred1 @sabaronett 
Have you guys discussed about this project? When will you start to work on it?

**Comment by sabaronett** [comment]
@qzhu2017 
Yeah, I met with Dean yesterday and discussed my first steps with Flask development. I plan to start work by this weekend.

**Comment by sayred1** [comment]
@sabaronett on my branch there are many more .cif files you can test https://github.com/qzhu2017/XRD/tree/dean/data. I've also uploaded a demo-profiling script.

**Comment by qzhu2017** [comment]
@sabaronett I just tried the recent commit.

I suggest the following improvements
- Add a few new menus:
    - FWHM
    - Profiling functions (this is a drop down menu)

- after I upload the cif structure and enter the parameters, it does show the interactive structure. However, I am asked to re-upload the structure if I want to recompute the PXRD with the modified parameters (e.g., wavelength)

**Comment by sayred1** [comment]
@sabaronett would you still like me to put together a logic tree for profiling or is the jupyter notebook sufficient?

**Comment by sabaronett** [comment]
@qzhu2017 
- Additional menus and advanced profiling: #22
- Re-upload issue: #20 

@sayred1 
That should be good for now. I'll let you know if I end up having any questions, something's not clear, or I need any more information.

Created #21 to track more specific goals for VXRD.
