### ISSUE TITLE
Clean up the repo after ***

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/XRD#14]
Need to clean up the files after
- XRD profile with proper fwhm
- Interactive XRD plot

**Comment by qzhu2017** [comment]
I just made some commits to reorganize the code. Now, the xrd code should be available via `python setup.py install`
After the code is done, I suggest the following layout.
```
flask
notebooks
dataset
pyxtal_xrd
├── __init__.py
├── XRD.py
├── database
├── similarity.py
│   ├── atomic_scattering_params.json
│   └── element.py
└── version.py
```

@sayred1 
I have greatly simplified the XRD code.
Also, I suggest a separate class to handle the profile function in XRD. The current code is a bit messy.

@sabaronett 
For flask, it would be good if you can move all relevant files to a separate folder later.

**Comment by sabaronett** [comment]
@qzhu2017, sounds good. I'll add that to my task list.

**Comment by sayred1** [comment]
@qzhu2017 Stan and I have completed cleaning up the repo, let us know what you think.

I may not have much time to work tomorrow since I have 2 assignments due on Sunday, and some reading to do. I plan on finishing these tomorrow, and picking up again on Saturday.

Thanks,

**Comment by qzhu2017** [comment]
@sayred1 
Did you complete the profile function?

**Comment by sayred1** [comment]
@qzhu2017 yes: https://github.com/qzhu2017/XRD/blob/master/pyxtal_xrd/profile.py.

If you want to test the profiling/similarity of validation set, just run `python -m scripts.checkStructures.py` in the top directory.  

I plan on doing most of the coding, particularly the bayesian optimization, in the `scripts` folder.

**Comment by qzhu2017** [comment]
@sayred1 
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/29445366/74001976-632f9580-4922-11ea-85a1-8a63c72cbfb6.png">
It shows that the last update is from me 2 days ago.

Please be more organized. Also, sometimes I still saw you upload some __pycache__ files.

**Comment by sayred1** [comment]
@qzhu2017 this is odd, here is an image of mine:

<img width="1146" alt="Screen Shot 2020-02-06 at 11 46 47 PM" src="https://user-images.githubusercontent.com/35546511/74010763-10aea300-493b-11ea-8df6-b61b59eab13e.png">

@sabaronett , your repo has updated to our recent changes, right?

**Comment by qzhu2017** [comment]
@sayred1 I don't know what you are doing!
https://github.com/qzhu2017/XRD/blob/master/pyxtal_xrd/profile.py
This link shows that the most recent update was from me
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/29445366/74011151-f2957280-493b-11ea-81d0-9c56fc5d3c7e.png">

The screen shot which you showed does not tell anything about the profile.py!

**Comment by qzhu2017** [comment]
> @qzhu2017 yes: https://github.com/qzhu2017/XRD/blob/master/pyxtal_xrd/profile.py.
> 
> If you want to test the profiling/similarity of validation set, just run `python -m scripts.checkStructures.py` in the top directory.

@sayred1 
I tried to to run this. However, I saw a lot of strange plots. What do you want to tell here?

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/29445366/74183465-daeb1200-4bf9-11ea-9403-d1b337087afc.png">

**Comment by qzhu2017** [comment]
@sayred1 You messed up the XRD.py after merge. Please be aware what you are doing!
