### ISSUE TITLE
XRD w/ Numba

### ISSUE THREAD

**Issue by sayred1** [qzhu2017/XRD#23]

**Comment by sayred1** [comment]
The distribution of times each function in XRD.py are as follows:
self.all_dhkl(): 0.0014946460723876953
self.intensity(): 0.10586690902709961
self.pxrdf(): 0.00044083595275878906
self.get_profile(): 50.00816059112549 (for function = split-type)

After wrapping self.get_profile(), the computation time decreases to 1.2611253261566162.

**Comment by qzhu2017** [comment]
@sayred1 Is this done?
