### ISSUE TITLE
Factors & Profiling Functions

### ISSUE THREAD

**Issue by sayred1** [qzhu2017/XRD#8]
To do:

- ~Debeye-Waller Factor: will not include, tabulated values only for unique cases~
- ~Absorption factor: will not include, too much to consider~
- ~Profiling functions: http://prism.mit.edu/xray/oldsite/4%20Profile%20Fitting%20for%20Quantitative%20Analysis.pdf included~

- Preferred orientation: May or may not include, explore literature folder in repo

**Comment by sayred1** [comment]
@qzhu2017 

Just want to give you an update on what I've done since our last meeting.
In our last meeting we discussed that I should look into the absorption coefficient, the preferred orientation coefficient, and applying the profiling functions.
I'm trying to balance my time out evenly between finals and research, so all I have done is read more into the absorption coefficient, here's what I've found:

In principle, calculation for the absorption coefficient (A) is simple, it's a function of the linear absorption coefficient (L) which is defined as a fraction of a beam of radiation absorbed per unit thickness of absorber. Normally, L is not tabulated but it can be found from intensity measurements in the lab, however there is a relationship between L and the mass absorption coefficients (M). M is a material dependent coefficient that is defined as L divided by the density of the crystal. For most Elements, M is tabulated at different photon wavelengths/energies (https://physics.nist.gov/PhysRefData/XrayMassCoef/tab3.html), but is not tabulated for crystals, so using tabulated element values will be an approximation. Further, since our XRD code relies on some input wavelength, we'd only be able to calculate M for certain wavelengths meaning that the user can only use A in strict cases (cases controlled by the tabulated values).

With that being said, let me know if you'd still like to add this option. I will now look into the preferred orientation and profiling functions this small break.

**Comment by qzhu2017** [comment]
@sayred1 
From the tabulated values, you can then do interpolation to obtain the M for any arbitrary wavelength.
I am not sure if you will apply A on each atom or on the structure. If you only apply the correction on the atom. I think you should include it.

Btw, I don't like the way you are working now. If you have trouble in focusing.  Please work on the project when you are fully done with the final. I expect you can focus on this project and quickly complete the project in a few days. Not spend a few hrs and then do something else. Also, try to frequently update the code. It is hard for me to check your progress without seeing the code.
