### ISSUE TITLE
XRD is not consistent with Mercury

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/XRD#9]
@sayred1 
I tried to use the same file (NaCl.cif) to compute the XRD, and compared it with Mercury. 8971765

The results are shown below. Clearly, we have a significant off for the 3rd peak. Could you just focus on that peak and recheck if the intensity is calculated correctly? I am thinking if this is because we missed some correction term or simply because we messed some expression in the current correction terms. 

<img width="806" alt="image" src="https://user-images.githubusercontent.com/29445366/71913648-c617ec00-312c-11ea-8acb-64d4599a00a9.png">

Please do this in time. If you are not clear about my concern, please talk to me. We have wasted a lot of time.

**Comment by sayred1** [comment]
I went in and looked our intensity calculations, there was a single line of code that needed to be fixed    at line **701** that accounts for multiplicity. https://github.com/qzhu2017/XRD/blob/0784b0f41726e762aa0c51712478dcf3ba16ede7/XRD.py#L692-L702.

Here's what the pxrd and mercury comparison looks like now:

<img width="983" alt="Screen Shot 2020-01-07 at 5 51 25 PM" src="https://user-images.githubusercontent.com/35546511/71943722-65150600-3176-11ea-8a99-34363f2e7173.png">

This is without preferred orientation. Our and mercurys profile functions still seem to be very different than one another in terms of intensities, and also have a slight shift in 2theta values. Notice also that both simulated peaks line up in 2theta, and that mercurys simulated peak is also slightly shifted from its profile function.

I crosschecked out pxrd intensities and 2thetas with pymatgen, everything seems to line up. 

<img width="979" alt="Screen Shot 2020-01-07 at 5 54 54 PM" src="https://user-images.githubusercontent.com/35546511/71943863-d8b71300-3176-11ea-967a-83d600c87eaf.png">

If we alter the march parameter, for instance I set the march parameter `_G = 0.63` in `similarity.ipynb`, this is what we get:

<img width="979" alt="Screen Shot 2020-01-07 at 6 16 38 PM" src="https://user-images.githubusercontent.com/35546511/71944846-e5893600-3179-11ea-9855-35266bb5d41f.png">

Obviously preferred orientation has a significant impact. But if you play with the march parameter, there isn't a value at which all simulated intensities from pxrd and mercury xrd line up, so we may be missing another correction factor that mercury has.

I also added another profiling function, https://en.wikipedia.org/wiki/Voigt_profile, which I believe is the function that mercury uses.

**Comment by qzhu2017** [comment]
@sayred1 , following our video discussion. I suspect the broadening of the peak is related to the theta angle by
<img width="998" alt="image" src="https://user-images.githubusercontent.com/29445366/71956726-c2be4800-31a0-11ea-8d33-adc42bbb9c32.png">
I got the relation from a quick on-line search
http://www.fhi-berlin.mpg.de/acnew/department/pages/teaching/pages/teaching__wintersemester__2015_2016/frank_girgsdies__peak_profile_fitting_in_xrd__151106.pdf

So, suppose the sample has a fixed size (p), the `bcos(theta)` term should be constant. Therefore, the peak at high angle will have bigger broadening. So the intensity should drop.

I am not sure if this is just a simple `cos(theta)`. But I just tried to rescale your data by `cos(theta)`. The results look comparable with Mercury results.

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/29445366/71956574-5f341a80-31a0-11ea-94d6-222a42bc6fce.png">

<img width="998" alt="image" src="https://user-images.githubusercontent.com/29445366/71957179-e1710e80-31a1-11ea-8cb6-85a37cc8926c.png">

Please further check if my relation is correct.

**Comment by qzhu2017** [comment]
@sayred1 Okay, I just found a very concise (but very useful) tutorial which clears my concerns regarding the issues appeared in our discussion.

http://prism.mit.edu/xray/introduction%20to%20xrpd%20data%20analysis.pdf

The peak shift follows a cosθ behavior, so peak shift might change direction over a large angular range.
